version: "3.9"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/
    ports:
      - "10000:8888"
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
volumes:
  postgres_data:
